export const projects = [
  {
    id: '1',
    title: 'Power Pulse',
    poster: 'https://i.postimg.cc/1zNtjRz2/Power-Pulse.jpg',
    description:
      'A convenient web application for people with a healthy lifestyle. This app will help you establish a healthy diet and exercise',
    languages: ['JavaScript', 'CSS'],
    libraries: ['React.js', 'Redux', 'Emotion', 'Axios', 'Formik'],
    responsive: 'Yes',
    git: 'https://github.com/YuriyAtamanenko/GachiClub',
    link: 'https://yuriyatamanenko.github.io/GachiClub/',
    teamOrPersonal: 'Team project',
  },
  {
    id: '2',
    title: 'Rental Car',
    poster: 'https://i.postimg.cc/gcK05TYz/Car-Rental.jpg',
    description:
      'Web application for car rental. In this application, you can filter cars by the selected options and save to favorites',
    languages: ['TypeScript', 'HTML', 'CSS'],
    libraries: ['React.js', 'Redux', 'Emotion', 'Axios', 'Prop-type'],
    responsive: 'No',
    git: 'https://github.com/YuriyAtamanenko/CarRentalApp',
    link: 'https://yuriyatamanenko.github.io/CarRentalApp/',
    teamOrPersonal: 'Personal project',
  },
  {
    id: '3',
    title: 'Cinemania',
    poster: 'https://i.postimg.cc/nhWr29nq/Cinemania.jpg',
    description:
      'A movie search app. Allows you to get full information about the movie and watch the trailer. A website with a responsive layout',
    languages: ['JavaScript', 'SCSS', 'HTML'],
    libraries: ['Axios', 'Parcel', 'Tui-pagination', 'Simplelightbox'],
    responsive: 'Yes',
    git: 'https://github.com/YuliaMoore/cine-spark',
    link: 'https://yuliamoore.github.io/cine-spark/',
    teamOrPersonal: 'Team project',
  },
  {
    id: '4',
    title: 'Carpathians Travel',
    poster: 'https://i.postimg.cc/Hn3syVSc/Carp-Travel.jpg',
    description: '',
    languages: ['TypeScript', 'CSS'],
    libraries: ['Next.js', 'TailwindCSS', 'Swiper'],
    responsive: 'No',
    git: 'https://github.com/YuriyAtamanenko/carp-travel-app',
    link: 'https://carp-travel-app.vercel.app/',
    teamOrPersonal: 'Personal project',
  },
  {
    id: '5',
    title: 'Phonebook',
    poster: 'https://i.postimg.cc/tTQTQ0ZT/Phonebook.jpg',
    description: 'Application for storing important contacts',
    languages: ['JavaScript', 'HTML', 'CSS'],
    libraries: ['React.js', 'Redux', 'Emotion', 'Axios', 'Notiflix'],
    responsive: 'No',
    git: 'https://github.com/YuriyAtamanenko/Phonebook',
    link: 'https://yuriyatamanenko.github.io/Phonebook/',
    teamOrPersonal: 'Personal project',
  },
  {
    id: '6',
    title: 'Phonebook API',
    poster: 'https://i.postimg.cc/Z5n06xzT/API.jpg',
    description:
      'This REST API is used for the Phonebook application. Performs user registration and login, and adds, deletes, and changes contacts',
    languages: ['JavaScript', 'Node.js'],
    libraries: [
      'Express',
      'Mongoose',
      'Morgan',
      'Multer',
      'Cross-env',
      'Bcrypt',
      'Sendgrid/mail',
      'Dotenv',
      'Jimp',
      'Joi',
      'Jsonwebtoken',
    ],
    responsive: '-',
    git: 'https://github.com/YuriyAtamanenko/Phonebook-API',
    link: 'https://yuriyatamanenko.github.io/Phonebook/',
    teamOrPersonal: 'Personal project',
  },
  {
    id: '7',
    title: 'Ice Cream',
    poster: 'https://i.postimg.cc/ZR8qJfpL/IceCream.jpg',
    description: '',
    languages: ['JavaScript', 'SCSS', 'HTML'],
    libraries: ['Modern-normalize'],
    responsive: 'Yes',
    git: 'https://github.com/serdcelosya/ice-team',
    link: 'https://serdcelosya.github.io/ice-team/',
    teamOrPersonal: '',
  },
  {
    id: '8',
    title: 'WebStudio',
    poster: 'https://i.postimg.cc/tJ94JhzG/Web-Studio.jpg',
    description: 'Website for WebStudio with responsive layout.',
    languages: ['HTML', 'CSS'],
    libraries: ['-'],
    responsive: 'Yes',
    git: 'https://github.com/YuriyAtamanenko/WebStudio',
    link: 'https://yuriyatamanenko.github.io/WebStudio/',
    teamOrPersonal: 'Personal project',
  },
];
